# NAVIGATION
bind = $mainMod, F, exec, $browser

# DEVELOPMENT
bind = $mainMod, D, exec, $editor

# SYSTEM TOOLS
bind = $mainMod, E, exec, $explorer
bind = $mainMod, Q, exec, $terminal
bind = $mainMod SHIFT, Q, exec, [float; size 800 450; center] $terminal
bind = $mainMod SHIFT, ESCAPE, exec, swaync-client -t -sw



