# SESSION / SYSTEM
bind = $mainMod, L, exec, hyprlock
bind = $mainMod, Delete, exit
bind = $mainMod, ESCAPE, exec, $scriptsDir/powermenu.sh

# LAUNCHER
bind = $mainMod, R, exec, $scriptsDir/launcher.sh

# CLIPBOARD
bind = $mainMod, V, exec, $scriptsDir/clipboard.sh -c
bind = $mainMod SHIFT, V, exec, $scriptsDir/clipboard.sh

# WALLPAPER
bind = $mainMod SHIFT, W, exec, $scriptsDir/wallpaper.sh --select
bind = $mainMod SHIFT, A, exec, $scriptsDir/wallpaper.sh --prev
bind = $mainMod SHIFT, D, exec, $scriptsDir/wallpaper.sh --next

# ZOOM
bind = $mainMod ALT, mouse_down, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 2.0}')"
bind = $mainMod ALT, mouse_up, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 2.0}')"

# SCREENSHOTS
bind = $mainMod, PRINT, exec, hyprshot -m window -f $(date +%Y-%m-%d_%H-%M-%S).png -o ~/Pictures/screenshots
bind = $mainMod SHIFT, PRINT, exec, hyprshot -m region -f $(date +%Y-%m-%d_%H-%M-%S).png -o ~/Pictures/screenshots
