# WINDOW MANAGEMENT
bind = $mainMod, X, killactive
bind = $mainMod, W, togglefloating
bind = $mainMod, J, togglesplit
bind = $mainMod, SPACE, fullscreen, 1
bind = $mainMod SHIFT, SPACE, fullscreen
bind = $mainMod, P, pseudo
bind = $mainMod, bracketleft, splitratio, -0.05
bind = $mainMod, bracketright, splitratio, +0.05

# WINDOW MOVEMENT
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, L, movewindow, r

# WINDOW FOCUS
bind = $mainMod, Left, movefocus, l
bind = $mainMod, Right, movefocus, r
bind = $mainMod, Up, movefocus, u
bind = $mainMod, Down, movefocus, d

# WINDOW RESIZE
binde = $mainMod Shift, Right, resizeactive, 30 0
binde = $mainMod Shift, Left, resizeactive, -30 0
binde = $mainMod Shift, Up, resizeactive, 0 -30
binde = $mainMod Shift, Down, resizeactive, 0 30

# MOUSE DRAG WINDOW MOVE/RESIZE
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

