add_newline = false
format = """\
  󰣇 \
  $directory\
  $git_branch$git_commit$git_state $git_status\
  $character\n
"""

right_format = """
$singularity\
$kubernetes\
$vcsh\
$hg_branch\
$pijul_channel\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$cpp\
$kotlin\
$ocaml\
$pixi\
$rlang\
$php\
$crystal\
$custom\
$status\
$os\
$time"""

continuation_prompt = '▶▶ '

[directory]
disabled = false
format = "[$path](bold fg:#8be9fd)"
truncate_to_repo = false
# home_symbol = "" 

[git_branch]
format = " [  $branch](fg:#9198a1)"

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[( $all_status$ahead_behind )](fg:#769ff0)]($style)'
style = "bg:#394260"

[time]
disabled = false
format = '[[  $time ](fg:#a0a9cb )]($style)'
time_format = "%R"                            # Hour:Minute Format
