windowrule = float on, match:initial_class ^(float)$
windowrule = float on, match:initial_title ^(Open File)$
windowrule = float on, match:initial_title ^(Open Folder)$
windowrule = float on, match:initial_title ^(Open Files)$
windowrule = float on, match:initial_title ^(Open)$
windowrule = float on, match:initial_title ^(Save File)$
windowrule = float on, match:initial_title ^(Save)$
windowrule = float on, match:title .*Sign.*