# ========================================
# INPUT CONFIGURATION
# ========================================

input {
    kb_layout = br
    kb_variant = abnt2
    follow_mouse = 1

    touchpad {
        natural_scroll = true
        scroll_factor = 0.69
    }
}
